# https://docs.spring.io/spring-cloud-stream/reference/rabbit/rabbit_overview/putting-it-all-together.html#page-title
configs:
  amqp:
    bindings:
      mgmtIntegrationSyncing: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_BINDINGS_MGMTINTEGRATIONSYNCING:mgmtIntegrationSyncing}
      pendingSyncingOut: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_BINDINGS_PENDINGSYNCINGOUT:pendingSyncingOut}

spring:
  cloud:
    stream:
      output-bindings: # we need explicit bindings bc we use StreamBridge
        - ${configs.amqp.bindings.mgmtIntegrationSyncing}
        - ${configs.amqp.bindings.pendingSyncingOut}
      bindings:
        mgmtIntegrationSyncing:
          destination: ${A6_MGMT_INTEGRATIONS_RABBITMQ_OUTPUT_MGMTINTEGRATIONSYNCING_EXCHANGE:mgmtIntegrationSyncing} # existing exchange
        pendingSyncingOut:
          destination: ${A6_MGMT_INTEGRATIONS_RABBITMQ_OUTPUT_PENDINGSYNCINGOUT_EXCHANGE:pendingSyncing} # existing exchange
        pendingSyncing-in-0:
          destination: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_PENDINGINTEGRATIONS_INPUT_EXCHANGE:pendingSyncing} # existing exchange (or creates)?
          group: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_PENDINGINTEGRATIONS_INPUT_QUEUE:reprocessing}
          binder: a6Rabbit
        tasksSyncingCorrespondence-in-0:
          destination: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_TASKSSYNCINGCORRESPONDENCE_INPUT_EXCHANGE:mgmtTasksSyncing} # existing exchange (or creates)?
          group: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_TASKSSYNCINGCORRESPONDENCE_INPUT_QUEUE:mgmtIntegrationCorrespondence}
          binder: a6Rabbit
      rabbit:
        bindings:
          mgmtIntegrationSyncing:
            producer:
              republishToDlq: false
          pendingSyncing-in-0:
            consumer:
              republishToDlq: false
          tasksSyncingCorrespondence-in-0:
            consumer:
              republishToDlq: false
          pendingSyncingOut:
            producer:
              republishToDlq: false
      binders:
        a6Rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${A6_MGMT_INTEGRATIONS_RABBITMQ_HOST:localhost}
                port: ${A6_MGMT_INTEGRATIONS_RABBITMQ_PORT:5672}
                username: ${A6_MGMT_INTEGRATIONS_RABBITMQ_USER:guest}
                password: ${A6_MGMT_INTEGRATIONS_RABBITMQ_PASSWORD:guest}
                virtual-host: ${A6_MGMT_INTEGRATIONS_RABBITMQ_VHOST:/}
    function:
      definition: pendingSyncing;tasksSyncingCorrespondence