spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${A6_PROJECTS_MGMT_INTEGRATIONS_OAUTH_SECURITY_ISSUER_URI:http://localhost:10100}

configs:
  security:
    secretKey: ${A6_PROJECTS_MGMT_INTEGRATIONS_SECURITY_SECRET_KEY}