configs:
  source:
    sourceConfigs:
      trello:
        registrationStrategy: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_REGISTRATIONSTRATEGY:redirectAuthorization}
        strategyConfigs:
          # GENERAL
          apiKey: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_APIKEY:TrelloApiKey}
          appName: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_APPNAME:AngoraSix}
          pluginId: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_PLUGINID}
          # REGISTRATION
          authorizationUrlPattern: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_AUTHORIZATIONURLPATTERN:https://trello.com/1/authorize?expiration=30days&name=:appName&scope=read&response_type=token&key=:apiKey&callback_method=fragment&return_url=:redirectUri}
          memberUrl: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_MEMBERURL:https://api.trello.com/1/members/me?fields=id}
          memberBoardsUrl: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_MEMBERBOARDSURL:https://api.trello.com/1/members/me/boards?fields=id,name,desc,closed,idOrganization,pinned,url,shortUrl,shortLink}
          boardListsUrlPattern: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_BOARDLISTSURLPATTERN:https://api.trello.com/1/boards/:boardId/lists?filter=open}
          boardCardsUrlPattern: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_BOARDCARDSURLPATTERN:https://api.trello.com/1/boards/:boardId/cards?limit=:limit&since=:since&pluginData=true&fields=&fields=id,name,desc,closed,idList,url,shortUrl,shortLink,due,dueComplete,idMembers}
          boardMembersUrlPattern: ${A6_PROJECTS_MGMT_INTEGRATIONS_INTEGRATION_TRELLO_BOARDMEMBERSURLPATTERN:https://api.trello.com/1/boards/:boardId/members?fields=id,username,fullName,url,email,avatarUrl}
    supported:
      - trello
